sudo: required
services:
  - docker

before_install:
  - docker build -t nagamalli/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nagamalli/react-test npm test -- --coverage
deploy:
  provider: elasticbeanstalk
  app: "multi-docker"
  region: "us-west-2"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-570015046342"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
